export type ThemeName = 'halloween' | 'christmas' | 'cyberpunk' | 'aurora' | 'minimal' | 'vaporwave'

export const allDecorations = [
  { src: '/decorations/halloween-1.gif', label: 'Ojo' },
  { src: '/decorations/halloween-2.gif', label: 'Calabaza' },
  { src: '/decorations/halloween-3.gif', label: 'Creepy' },
  { src: '/decorations/halloween-4.gif', label: 'Gato' },
  { src: '/decorations/christmas-1.gif', label: 'Padoru' },
  { src: '/decorations/emoji-shock.gif', label: 'Emoji' },
  { src: '/decorations/linux-computer.gif', label: 'Linux' },
  { src: '/decorations/christmas-3.gif', label: 'Santa' },
  { src: '/decorations/link-shades.gif', label: 'Link' },
  { src: '/decorations/Fer.gif', label: 'Fernando' },
  { src: '/decorations/Franco.gif', label: 'Franco' },
  { src: '/decorations/mark-grayson.gif', label: 'Mark' },
  { src: '/decorations/abstract-art.gif', label: 'Art' },
  { src: '/decorations/mechanics.gif', label: 'Mech' },
  { src: '/decorations/marlb.gif', label: 'Marl' },
  { src: '/decorations/tje.gif', label: 'Tje' }
]

export const profileThemes = {
  halloween: {
    card: 'bg-gradient-to-br from-orange-800 via-red-800 to-black border-4 border-orange-500 shadow-2xl relative overflow-hidden',
    title: 'text-orange-200 drop-shadow-lg font-black text-4xl',
    stats: ['text-orange-300', 'text-purple-300', 'text-red-300', 'text-yellow-300'],
    bio: 'bg-gradient-to-r from-orange-600/60 to-red-600/60 border-3 border-orange-400 shadow-inner backdrop-blur-sm',
    bioText: 'text-orange-200',
    button: 'bg-gradient-to-r from-orange-600 to-red-600 border-2 border-orange-400 hover:from-orange-700 hover:to-red-700 text-white shadow-lg hover:shadow-xl font-bold transition-all',
    statBox: 'bg-black/30 border-2 border-orange-400/50 backdrop-blur-sm shadow-lg',
    statLabel: 'text-orange-100',
    postCard: 'border-orange-400/50 bg-gradient-to-br from-orange-500/20 to-red-500/20',
    postText: 'text-gray-900',
    postTitle: 'text-orange-900 group-hover:text-orange-700',
    postExcerpt: 'text-gray-800',
    postCategory: 'bg-orange-500/80 text-gray-900 font-bold',
    postPinned: 'bg-orange-600 text-gray-900 font-bold',
    postDate: 'text-gray-700',
    sectionTitle: 'text-orange-100',
    sectionSubtitle: 'text-orange-200',
    emojis: ['🎃', '🕷️', '💀', '🦇', '👻', '🕸️'],
    background: 'from-black via-orange-900 to-red-900',
    avatarBorder: 'border-orange-500 ring-4 ring-orange-500/50 shadow-2xl shadow-orange-500/50',
    username: 'text-orange-100',
    emptyIcon: 'text-orange-400'
  },
  christmas: {
    card: 'bg-gradient-to-br from-[#1d351d] via-[#325632] to-[#8b181d] border-4 border-[#e6be9a] shadow-2xl relative overflow-hidden',
    title: 'text-[#f5e2c8] drop-shadow-lg font-black text-4xl',
    stats: ['text-[#e6be9a]', 'text-[#e6be9a]', 'text-[#e6be9a]', 'text-[#e6be9a]'],
    bio: 'bg-gradient-to-r from-[#325632]/60 to-[#8b181d]/60 border-3 border-[#e6be9a] shadow-inner backdrop-blur-sm',
    bioText: 'text-[#f5e2c8]',
    button: 'bg-gradient-to-r from-[#8b181d] to-[#6f0f11] border-2 border-[#e6be9a] hover:from-[#a02025] hover:to-[#8b1a1d] !text-[#f5e2c8] shadow-lg hover:shadow-xl font-bold transition-all',
    statBox: 'bg-[#1d351d]/50 border-2 border-[#e6be9a]/50 backdrop-blur-sm shadow-lg',
    statLabel: 'text-[#e6be9a]',
    postCard: 'border-[#e6be9a]/50 bg-gradient-to-br from-[#325632]/30 to-[#8b181d]/30',
    postText: 'text-gray-900',
    postTitle: 'text-[#6f0f11] group-hover:text-[#8b181d]',
    postExcerpt: 'text-gray-800',
    postCategory: 'bg-[#8b181d]/80 text-gray-100 font-bold',
    postPinned: 'bg-[#6f0f11] text-gray-100 font-bold',
    postDate: 'text-gray-700',
    sectionTitle: 'text-[#e6be9a]',
    sectionSubtitle: 'text-[#e6be9a]/80',
    emojis: ['🎄', '❄️', '⭐', '🎁', '🎅', '🔔'],
    background: 'from-[#1d351d] via-[#325632] to-[#1d351d]',
    avatarBorder: 'border-[#8b181d] ring-4 ring-[#e6be9a]/50 shadow-2xl shadow-[#8b181d]/50',
    avatarDecoration: '/themes/christmas-hat.png',
    username: 'text-[#e6be9a]',
    emptyIcon: 'text-[#e6be9a]'
  },
  cyberpunk: {
    card: 'bg-gradient-to-br from-slate-950 via-purple-950 to-black border-4 border-cyan-400 shadow-2xl shadow-cyan-500/50 relative overflow-hidden',
    title: 'text-cyan-300 drop-shadow-lg font-black text-4xl',
    stats: ['text-cyan-300', 'text-purple-300', 'text-pink-300', 'text-yellow-300'],
    bio: 'bg-gradient-to-r from-slate-900/60 to-purple-900/60 border-3 border-cyan-400 shadow-inner backdrop-blur-sm',
    bioText: 'text-cyan-300',
    button: 'bg-gradient-to-r from-cyan-600 to-purple-600 border-2 border-cyan-400 hover:from-cyan-700 hover:to-purple-700 text-white shadow-lg shadow-cyan-500/50 hover:shadow-xl font-bold transition-all',
    statBox: 'bg-black/50 border-2 border-cyan-400/60 backdrop-blur-sm shadow-lg shadow-cyan-400/20',
    statLabel: 'text-cyan-200',
    postCard: 'border-cyan-400/50 bg-gradient-to-br from-cyan-500/20 to-purple-500/20',
    postText: 'text-slate-950',
    postTitle: 'text-slate-950 group-hover:text-slate-800',
    postExcerpt: 'text-slate-900',
    postCategory: 'bg-cyan-500/80 text-slate-950 font-bold',
    postPinned: 'bg-cyan-600 text-slate-950 font-bold',
    postDate: 'text-slate-800',
    sectionTitle: 'text-cyan-300',
    sectionSubtitle: 'text-cyan-200',
    emojis: ['⚡', '🌃', '💻', '🔮', '🎮', '🌐'],
    background: 'from-slate-950 via-purple-950 to-black',
    avatarBorder: 'border-cyan-300 ring-cyan-500/50',
    username: 'text-cyan-200',
    emptyIcon: 'text-cyan-400'
  },
  aurora: {
    card: 'bg-gradient-to-br from-emerald-600 via-cyan-500 to-violet-600 border-4 border-emerald-300 shadow-2xl shadow-emerald-500/50 relative overflow-hidden',
    title: 'text-white drop-shadow-lg font-black text-4xl',
    stats: ['text-emerald-100', 'text-cyan-100', 'text-violet-100', 'text-sky-100'],
    bio: 'bg-gradient-to-r from-emerald-600/50 to-violet-600/50 border-3 border-emerald-300 shadow-inner backdrop-blur-sm',
    bioText: 'text-yellow-300',
    button: 'bg-gradient-to-r from-emerald-500 to-cyan-500 border-2 border-cyan-300 hover:from-emerald-600 hover:to-cyan-600 text-white shadow-lg shadow-emerald-500/50 hover:shadow-xl font-bold transition-all',
    statBox: 'bg-white/15 border-2 border-emerald-300/60 backdrop-blur-sm shadow-lg',
    statLabel: 'text-emerald-100',
    postCard: 'border-emerald-400/50 bg-gradient-to-br from-emerald-500/20 to-violet-500/20',
    postText: 'text-emerald-950',
    postTitle: 'text-emerald-900 group-hover:text-emerald-700',
    postExcerpt: 'text-emerald-800',
    postCategory: 'bg-emerald-500/80 text-emerald-950 font-bold',
    postPinned: 'bg-emerald-600 text-emerald-950 font-bold',
    postDate: 'text-emerald-700',
    sectionTitle: 'text-emerald-100',
    sectionSubtitle: 'text-emerald-200',
    emojis: ['𓆝', '𓆟', '𓆞', '🌌', '🌠', '💫'],
    background: 'from-emerald-950 via-cyan-900 to-violet-950',
    avatarBorder: 'border-emerald-200 ring-emerald-400/50',
    username: 'text-emerald-100',
    emptyIcon: 'text-emerald-400'
  },
  minimal: {
    card: 'bg-white border border-gray-200 shadow-sm relative overflow-hidden',
    title: 'text-gray-900 font-bold text-4xl',
    stats: ['text-gray-900', 'text-gray-900', 'text-gray-900', 'text-gray-900'],
    bio: 'bg-gray-50 border border-gray-200',
    bioText: 'text-gray-700',
    button: 'bg-gray-900 border border-gray-900 hover:bg-gray-800 text-white shadow-sm hover:shadow-md font-medium transition-all',
    statBox: 'bg-gray-50 border border-gray-200',
    statLabel: 'text-gray-600',
    postCard: 'border-gray-200 bg-white',
    postText: 'text-gray-900',
    postTitle: 'text-gray-900 group-hover:text-gray-700',
    postExcerpt: 'text-gray-600',
    postCategory: 'bg-gray-900 text-white font-medium',
    postPinned: 'bg-gray-700 text-white font-medium',
    postDate: 'text-gray-500',
    sectionTitle: 'text-gray-900',
    sectionSubtitle: 'text-gray-600',
    emojis: ['·', '·', '·', '·', '·', '·'],
    background: 'from-gray-50 to-gray-100',
    avatarBorder: 'border-gray-900 ring-gray-200',
    username: 'text-gray-600',
    emptyIcon: 'text-gray-400'
  },
  vaporwave: {
    card: 'bg-gradient-to-br from-pink-400 via-purple-400 to-cyan-400 border-4 border-pink-300 shadow-2xl shadow-pink-500/50 relative overflow-hidden',
    title: 'text-white drop-shadow-lg font-black text-4xl',
    stats: ['text-pink-100', 'text-purple-100', 'text-cyan-100', 'text-yellow-100'],
    bio: 'bg-gradient-to-r from-pink-500/50 to-purple-500/50 border-3 border-pink-300 shadow-inner backdrop-blur-sm',
    bioText: 'text-yellow-200',
    button: 'bg-gradient-to-r from-pink-500 to-purple-500 border-2 border-pink-300 hover:from-pink-600 hover:to-purple-600 text-white shadow-lg shadow-pink-500/50 hover:shadow-xl font-bold transition-all',
    statBox: 'bg-white/20 border-2 border-pink-300/60 backdrop-blur-sm shadow-lg',
    statLabel: 'text-pink-100',
    postCard: 'border-pink-300/50 bg-gradient-to-br from-pink-400/20 to-purple-400/20',
    postText: 'text-purple-950',
    postTitle: 'text-purple-900 group-hover:text-purple-700',
    postExcerpt: 'text-purple-800',
    postCategory: 'bg-pink-500/80 text-white font-bold',
    postPinned: 'bg-purple-600 text-white font-bold',
    postDate: 'text-purple-700',
    sectionTitle: 'text-pink-100',
    sectionSubtitle: 'text-purple-100',
    emojis: ['✨', '🌸', '💜', '🌊', '🎀', '💫'],
    background: 'from-pink-300 via-purple-300 to-cyan-300',
    avatarBorder: 'border-pink-300 ring-purple-400/50',
    username: 'text-pink-100',
    emptyIcon: 'text-pink-300'
  }
}

export const themeNames: { value: ThemeName; label: string; emoji: string }[] = [
  { value: 'halloween', label: 'Halloween', emoji: '🎃' },
  { value: 'christmas', label: 'Navidad', emoji: '🎄' },
  { value: 'cyberpunk', label: 'Cyberpunk', emoji: '🌃' },
  { value: 'aurora', label: 'Aurora', emoji: '🌌' },
  { value: 'minimal', label: 'Minimal', emoji: '⚪' },
  { value: 'vaporwave', label: 'Vaporwave', emoji: '🌸' }
]
